---
# Simple profile showing off the dependabot_configured rule
version: v1
type: profile
name: dependabot-pip-github-profile
display_name: Dependabot for Python projects
context:
  provider: github
alert: "on"
remediate: "off"
repository:
  - type: dependabot_configured
    def:
      package_ecosystem: pip
      schedule_interval: daily
      apply_if_file: requirements.txt