---
# Simple profile showing off the dependabot_configured rule
version: v1
type: profile
name: dependabot-npm-docs-github-profile
display_name: Dependabot for JavaScript projects
context:
  provider: github
alert: "off"
remediate: "on"
repository:
  - type: dependabot_configured
    def:
      package_ecosystem: npm
      schedule_interval: daily
      apply_if_file: package.json
