---
# Simple profile showing off the dependabot_configured rule
version: v1
type: profile
name: dependabot-npm-docs-github-profile
context:
  provider: github
alert: "on"
remediate: "on"
repository:
  - type: dependabot_configured
    def:
      package_ecosystem: npm
      schedule_interval: daily
      apply_if_file: docs/package.json
