---
# A profile to verify common security settings for GitHub workflows
version: v1
type: profile
name: workflow-security-github-profile
context:
  provider: github
alert: "on"
remediate: "off"
repository:
  - type: actions_check_pinned_tags
    def:
      exclude:
        - slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@1.9.0
  - type: default_workflow_permissions
    def:
      default_workflow_permissions: read
      can_approve_pull_request_reviews: true